nombre = input ("Introduce tu nombre: ")
apellido = input ("Introduce tu apellido: ")
edad= int(input("Introduce tu edad: "))
correo= input("Introduce tu correo electronico: ")
telefono= input("Introduce tu numero telefonico: ")

print("Nombre: "+ nombre)
print("Apellido: "+ apellido)
print("tengo " +str(edad)+"años")
print("Correo: "+ telefono)
